"""ShapeGraMM redundant-geometry sharing and transform compression.

From "ShapeGraMM: On the fly procedural generation of massive models for
real-time visualization" (Santos, Brazil, Raposo, 2023), Section 5.2. The
model-conversion pipeline applies three methods; this module implements two of
them deterministically:

  (ii) Sharing of redundant geometries -- following Ivson/Celes shape matching
       (paper ref [13]), objects whose meshes are identical up to an affine
       transform are clustered to share a single base geometry id. The paper
       reports huge redundancy: 11.1M total geometries collapse to ~101K unique
       (complex facility). We detect similarity (rigid + uniform-scale +
       reflection + vertex-ordering) redundancy via a pairwise-distance shape
       signature, which is invariant under those transforms.

  (iii) Object transform compression -- objects belonging to the same structure
        exhibit strong coherence: "a row of beams share the same scale,
        rotation, and colors; therefore they can be generated by a pair of
        translation and instance rules." We group objects by their shared
        (scale, rotation, color) and express each group as one base transform
        plus a list of translations, estimating the footprint reduction.

Deterministic: pure computation, no randomness.
"""

import math
from dataclasses import dataclass


# --------------------------------------------------------------------------
# (ii) Redundant geometry sharing
# --------------------------------------------------------------------------

def _pairwise_distances(vertices):
    dists = []
    n = len(vertices)
    for a in range(n):
        va = vertices[a]
        for b in range(a + 1, n):
            vb = vertices[b]
            dx = va[0] - vb[0]
            dy = va[1] - vb[1]
            dz = va[2] - vb[2]
            dists.append(math.sqrt(dx * dx + dy * dy + dz * dz))
    return dists


def geometry_signature(vertices, decimals=4):
    """Return a canonical shape signature invariant to similarity transforms.

    The signature is the sorted multiset of pairwise vertex distances scaled so
    the largest distance is 1, rounded to ``decimals``. This is invariant to
    translation, rotation, reflection, uniform scaling, and vertex ordering, so
    two meshes that differ only by such an affine transform yield equal
    signatures. The vertex count is included to avoid accidental collisions.
    """
    verts = tuple(tuple(float(c) for c in v) for v in vertices)
    n = len(verts)
    if n == 0:
        return (0, ())
    if n == 1:
        return (1, ())
    dists = _pairwise_distances(verts)
    scale = max(dists)
    if scale <= 1e-12:
        return (n, ())
    norm = tuple(sorted(round(d / scale, decimals) for d in dists))
    return (n, norm)


def share_geometries(objects, decimals=4):
    """Cluster objects that share a geometry up to an affine transform.

    ``objects`` is a sequence of ``(object_id, vertices)`` pairs. Returns
    ``(assignment, stats)`` where ``assignment`` maps ``object_id ->
    geometry_id`` (a stable ``"geom_<k>"`` label per unique signature, numbered
    in first-appearance order) and ``stats`` reports the total, unique and
    redundant counts plus the redundancy fraction.
    """
    assignment = {}
    sig_to_geom = {}
    order = 0
    for obj_id, verts in objects:
        sig = geometry_signature(verts, decimals=decimals)
        geom = sig_to_geom.get(sig)
        if geom is None:
            geom = "geom_%d" % order
            sig_to_geom[sig] = geom
            order += 1
        assignment[obj_id] = geom
    total = len(assignment)
    unique = len(sig_to_geom)
    redundant = total - unique
    stats = {
        "total": total,
        "unique": unique,
        "redundant": redundant,
        "redundant_fraction": (redundant / total) if total else 0.0,
    }
    return assignment, stats


# --------------------------------------------------------------------------
# (iii) Object transform compression
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class CompressedGroup:
    """A coherent group of objects sharing scale/rotation/color.

    Encoded as one base transform (``scale``, ``rotation``, ``color``) plus the
    list of ``translations`` -- the ShapeGraMM "pair of translation and
    instance rules" representation.
    """

    scale: tuple
    rotation: tuple
    color: tuple
    translations: tuple


def _key(rounded):
    return rounded


def compress_transforms(objects, decimals=4):
    """Compress coherent object transforms into base + translation lists.

    ``objects`` is a sequence of dicts/tuples with keys ``translation``,
    ``scale``, ``rotation``, ``color``. Objects sharing the same (rounded)
    scale, rotation and color are merged into one :class:`CompressedGroup`
    holding only their translations. Returns ``(groups, stats)``.

    ``stats`` estimates the footprint reduction: a full per-object transform
    stores scale+rotation+color+translation (12 float components here), while a
    compressed group stores one base (9 components) plus 3 per translation.
    """
    def rnd(v):
        return tuple(round(float(c), decimals) for c in v)

    buckets = {}
    order = []
    for obj in objects:
        scale = rnd(obj["scale"])
        rotation = rnd(obj["rotation"])
        color = rnd(obj["color"])
        translation = rnd(obj["translation"])
        key = (scale, rotation, color)
        if key not in buckets:
            buckets[key] = []
            order.append(key)
        buckets[key].append(translation)

    groups = []
    for key in order:
        scale, rotation, color = key
        groups.append(CompressedGroup(scale, rotation, color,
                                      tuple(buckets[key])))

    n = len(objects)
    # per-object footprint: 3 (scale) + 3 (rotation) + 3 (color) + 3 (trans)
    uncompressed = n * 12
    compressed = 0
    for g in groups:
        compressed += 9 + 3 * len(g.translations)
    stats = {
        "objects": n,
        "groups": len(groups),
        "uncompressed_components": uncompressed,
        "compressed_components": compressed,
        "compression_ratio": (compressed / uncompressed) if uncompressed else 1.0,
    }
    return tuple(groups), stats
