"""CADTalk label transfer — point-cloud max-vote / IoU labelling (Sec. 9.3).

Two places in CADTalk assign a label to a code block by comparing the block's
geometry to a labelled point set:

  * **Automatic ground-truth transfer** (Sec. 9.3): because the machine-made
    programs come from PartNet shapes, "we convert the corresponding PartNet
    shape into a point cloud with per-point labels, compare the part shape
    generated by each code block to the labelled point cloud by checking the IoU,
    and obtain the corresponding part label by maximum voting." Multiple valid
    labels are kept when a primitive genuinely spans several parts ("it may
    occupy both the wing and engine areas, we thus keep all valid labels").

  * **PartSLIP baseline aggregation** (Sec. 5.3): "Each block is assigned a label
    corresponding to most of the points it contains", after transferring
    per-point labels back to blocks via the block-point correspondence.

Both reduce to the same deterministic operation: given, for each block, the set
of labelled reference points that fall inside it, assign the majority label
(and/or every label whose share exceeds a threshold, for multi-label ground
truth). This module implements that, plus an IoU-based variant that scores a
block against each label's whole point set.

Pure stdlib; deterministic (ties broken by label sort order).
"""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, Hashable, Iterable, List, Mapping, Sequence, Set, Tuple

Point = Hashable  # a point id / coordinate tuple; only identity/equality used.


def majority_label(
    block_points: Mapping[int, Iterable[Point]],
    point_labels: Mapping[Point, str],
) -> Dict[int, str]:
    """Assign each block the label held by *most* of the points it contains
    (PartSLIP-style aggregation). Points absent from ``point_labels`` are
    ignored. Blocks with no labelled points are omitted. Ties -> label sort
    order."""
    out: Dict[int, str] = {}
    for block, pts in block_points.items():
        counts: Dict[str, int] = defaultdict(int)
        for p in pts:
            lab = point_labels.get(p)
            if lab is not None:
                counts[lab] += 1
        if not counts:
            continue
        best_count = max(counts.values())
        winners = sorted(l for l, c in counts.items() if c == best_count)
        out[block] = winners[0]
    return out


def multi_labels(
    block_points: Mapping[int, Iterable[Point]],
    point_labels: Mapping[Point, str],
    share: float = 0.25,
) -> Dict[int, Set[str]]:
    """Keep *all* labels whose share of a block's labelled points is at least
    ``share`` (multi-label ground truth, Sec. 9.3). Always keeps the majority
    label so no block ends up empty when it has labelled points."""
    out: Dict[int, Set[str]] = {}
    for block, pts in block_points.items():
        counts: Dict[str, int] = defaultdict(int)
        total = 0
        for p in pts:
            lab = point_labels.get(p)
            if lab is not None:
                counts[lab] += 1
                total += 1
        if total == 0:
            continue
        keep = {l for l, c in counts.items() if c / total >= share}
        if not keep:
            best = max(counts.values())
            keep = {sorted(l for l, c in counts.items() if c == best)[0]}
        out[block] = keep
    return out


def iou_label(
    block_points: Mapping[int, Iterable[Point]],
    point_labels: Mapping[Point, str],
) -> Dict[int, str]:
    """Assign each block the label of maximum IoU between the block's point set
    and that label's whole point set (Sec. 9.3, "checking the IoU ... maximum
    voting"). Ties -> label sort order."""
    label_sets: Dict[str, Set[Point]] = defaultdict(set)
    for p, lab in point_labels.items():
        label_sets[lab].add(p)
    out: Dict[int, str] = {}
    for block, pts in block_points.items():
        bset: Set[Point] = set(pts)
        if not bset:
            continue
        best_iou = -1.0
        best_lab = None
        for lab in sorted(label_sets):
            lset = label_sets[lab]
            union = bset | lset
            iou = len(bset & lset) / len(union) if union else 0.0
            if iou > best_iou:
                best_iou = iou
                best_lab = lab
        if best_lab is not None and best_iou > 0.0:
            out[block] = best_lab
    return out
