"""OCCT kernel-quirk catalog mined from the OCE/OCCT sources themselves.

Companion to :mod:`occt_quirks` (which catalogs quirks observed by OCCT
CLIENTS: cadquery, Roshera, Zoo, cadgenbench, OpenCAD). This module catalogs
quirks the KERNEL DEVELOPERS themselves recorded inside the OCCT source tree,
where scar tissue is marked not with the word "workaround" but with reviewer
tags (``//:abv``, ``pdn 17.03.99``, ``skl 15.05.2002``, ``gka 06.09.04``,
``rln``, ``jgv``) and Mantis bug ids (``OCC208``, ``OCC7630``, ``OCC20222``,
``OCC21772``, ``OCC26717``), usually citing the exact customer STEP/IGES file
that exposed the defect (``PRO10366``, ``BUC50070``, ``trj3_s1-ac-214.stp``,
``ug_exhaust-A.stp``).

Source repository:
  resources/cad_repos/oce-oce-patches/oce-oce-patches (the OCE fork tracking
  Open CASCADE Technology; modern module layout: ModelingAlgorithms/,
  DataExchange/, ModelingData/, ...).

License verdict of the mined repo: LGPL-2.1 (LICENSE_LGPL_21.txt) WITH the
Open CASCADE exception version 1.0 (OCCT_LGPL_EXCEPTION.txt), which permits
object-code use of header material under terms of your choice with notice.
This module copies NO code from that repository: each row records a FACT
about kernel behavior with a file citation and the reviewer tag / bug id
that marks it; any quoted comment text is under one sentence.

Pure stdlib, deterministic; no kernel, no model. The catalog is data for the
generation/repair loops (and prompt builders) to consult, never a kernel
shim itself.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

#: Root of the mined repository, used in every citation below.
OCE_REPO = "resources/cad_repos/oce-oce-patches/oce-oce-patches"


@dataclass(frozen=True)
class Quirk:
    """One catalogued kernel quirk: what breaks, when, and what to do instead."""

    id: str
    operation: str          # the op family the quirk bites (wire-heal/step-import/...)
    quirk: str
    trigger: str
    workaround: str
    source: str

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "operation": self.operation,
            "quirk": self.quirk,
            "trigger": self.trigger,
            "workaround": self.workaround,
            "source": self.source,
        }


OCE_QUIRKS: Tuple[Quirk, ...] = (
    # ------------------------------------------------------------------ #
    # ShapeFix_Wire: the densest scar-tissue file in the kernel
    # ------------------------------------------------------------------ #
    Quirk(
        id="fix-intersecting-edges-no-cut",
        operation="wire-heal",
        quirk="Cutting edges while fixing intersecting edges corrupts "
              "ADJACENT faces that share those edges; the fix for one face "
              "breaks its neighbours.",
        trigger="FixIntersectingEdges on a wire whose edges are shared with "
                "other faces (any imported shell).",
        workaround="Never shorten/cut shared edges during intersection "
                   "repair; increase vertex tolerance instead so the "
                   "intersection is swallowed by tolerance.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx (':j6 abv 7 Dec 98' ProSTEP TR10 "
               "r0601_id.stp #57676/#58586)",
    ),
    Quirk(
        id="nonadjacent-intersection-vertex-tol",
        operation="wire-heal",
        quirk="NON-adjacent edges of one wire can intersect (not just "
              "consecutive ones); splitting them creates regressions.",
        trigger="Self-intersecting imported wires where the crossing edges "
                "are not neighbours in the wire order.",
        workaround="Fix non-adjacent intersections by INFLATING the vertex "
                   "tolerance to cover the intersection point rather than "
                   "splitting edges.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx ('pdn 17.03.99' S4135, comment before "
               "FixIntersectingEdges(num1,num2))",
    ),
    Quirk(
        id="pcurve-self-intersection-loops",
        operation="pcurve",
        quirk="Pcurves acquire small self-intersection LOOPS after import/"
              "healing; the 3D curve is fine but the 2D image loops back on "
              "itself.",
        trigger="Wires read from STEP/IGES with pcurves regenerated by "
                "projection near tolerance-scale features.",
        workaround="Detect and remove self-interference loops on pcurves as "
                   "a dedicated wire-healing pass before face building.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx (':k3 abv 24 Dec 98' BUC50070 "
               "#26682/#30087)",
    ),
    Quirk(
        id="pcurve-shift-between-singularities",
        operation="pcurve",
        quirk="On surfaces with two singularities (e.g. sphere), a pcurve "
              "can land in the wrong period cell so the whole wire sits "
              "shifted in UV.",
        trigger="Wires on periodic/singular surfaces after import; edges "
                "parameterized near both singular points.",
        workaround="Shift the WHOLE wire (all pcurves together) by an "
                   "integer number of periods into the surface's natural "
                   "cell instead of fixing edges one by one.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx ('pdn 30.12.98' PRO10366 #210 and "
               "'pdn 17.12.98' FixShifted)",
    ),
    Quirk(
        id="shared-pcurve-inplace-transform-aliasing",
        operation="pcurve",
        quirk="Several edges may reference the SAME pcurve handle; "
              "transforming that pcurve in place silently moves every other "
              "edge that shares it.",
        trigger="Applying a UV translation/period shift to an edge's pcurve "
                "on shapes where healing reused one pcurve for many edges.",
        workaround="Never Transform() a pcurve in place: build a "
                   "Transformed() COPY and replace the edge's pcurve with "
                   "the copy.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx ('skl 15.05.2002 for OCC208', three "
               "ReplacePCurve sites)",
    ),
    Quirk(
        id="split-edge-in-singularity",
        operation="wire-heal",
        quirk="An edge passing THROUGH a surface singularity cannot get one "
              "consistent pcurve; single-pcurve repair fails.",
        trigger="Edges crossing the apex/pole of cones, spheres, "
                "degenerated torus regions after STEP import.",
        workaround="Split the edge AT the singularity so each half gets its "
                   "own pcurve on its side of the singular point.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx ('abv 24 Feb 00' trj3_s1-ac-214.stp "
               "#1631)",
    ),
    Quirk(
        id="self-intersection-appears-after-bend",
        operation="wire-heal",
        quirk="FixLacking's pcurve BENDING can INTRODUCE a self-intersection "
              "that was not detectable before the bend.",
        trigger="Closing a gap in a wire by bending pcurves (FixLacking) "
                "near other edges.",
        workaround="Re-run self-intersection and intersecting-edge checks "
                   "AFTER any pcurve bending, not only before.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx (':s3 abv 22 Apr 99' PRO7187 #11534; "
               "'skl 24.04.2003 for OCC58')",
    ),
    Quirk(
        id="degenerated-edge-no-pcurve-removal",
        operation="iges-import",
        quirk="IGES read can produce a degenerated edge that has NO pcurve; "
              "such an edge is unusable and poisons downstream fixes.",
        trigger="IGES files read with 3D preference (pref3d) containing "
                "degenerate topology.",
        workaround="Remove degenerated edges lacking a pcurve during wire "
                   "healing instead of trying to repair them.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Wire.cxx and ShapeAnalysis_Wire.cxx "
               "(':n2 abv 22.01.99' ma-test5.igs)",
    ),
    Quirk(
        id="closed-edge-must-not-become-degenerated",
        operation="wire-heal",
        quirk="An edge whose two vertices coincide within precision looks "
              "degenerated, but a CLOSED edge (full circle etc.) with a "
              "real 3D curve must not be marked degenerated.",
        trigger="Degenerate-edge detection on wires containing closed edges "
                "(circle-like) whose end vertices are the same point.",
        workaround="Before flagging an edge degenerated, check for an "
                   "existing 3D curve with genuine length; skip closed "
                   "edges.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeAnalysis/ShapeAnalysis_Wire.cxx ('abv 24 Feb 00' "
               "trj3_as1-ac-214.stp #6065)",
    ),
    Quirk(
        id="degenerated-flag-still-needs-pcurve-check",
        operation="wire-heal",
        quirk="An edge already MARKED degenerated and carrying a pcurve can "
              "still hold the WRONG pcurve relative to its neighbours.",
        trigger="Checking degenerated edges between two edges whose pcurves "
                "imply a different singular location.",
        workaround="Validate the degenerated edge's pcurve against the "
                   "adjacent edges' pcurve endpoints even when the "
                   "degenerated flag is already set.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeAnalysis/ShapeAnalysis_Wire.cxx ('skl 30.12.2004 for "
               "OCC7630')",
    ),
    # ------------------------------------------------------------------ #
    # ShapeFix_Face / ComposeShell / IntersectionTool
    # ------------------------------------------------------------------ #
    Quirk(
        id="missing-natural-bound-sphere-torus",
        operation="face-heal",
        quirk="Faces on full spheres/toruses can arrive WITHOUT their "
              "natural boundary wire, so containment/orientation logic "
              "misclassifies inner wires.",
        trigger="STEP/IGES faces built on closed analytic surfaces where "
                "the exporter omitted the natural bound.",
        workaround="Detect the missing natural boundary and ADD it "
                   "explicitly (FixAddNaturalBound) before orienting wires.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Face.cxx ('pdn 981202' sphere; ':abv 28.08.01' "
               "extended for toruses)",
    ),
    Quirk(
        id="makeface-isdegenerated-error",
        operation="face-heal",
        quirk="BRepLib_MakeFace's IsDegenerated handling is itself buggy: "
              "faces built from imported geometry keep bad degenerated "
              "status on edges.",
        trigger="Building faces during STEP import (natural-bound path).",
        workaround="After MakeFace, re-run the edge-fix tool over every "
                   "edge of the new face to rebuild degenerated status and "
                   "pcurves.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Face.cxx ('gka 11.01.99' PRO7755.stp #2018, "
               "'work-around error in BRepLib_MakeFace')",
    ),
    Quirk(
        id="small-face-precision-autocorrect",
        operation="face-heal",
        quirk="A fixed global precision is WRONG for very small faces: "
              "healing at file precision collapses features smaller than "
              "the tolerance.",
        trigger="Healing faces whose least edge size is comparable to the "
                "working precision.",
        workaround="Auto-correct the working precision per face from its "
                   "least edge size before healing (auto-correct precision "
                   "mode).",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Face.cxx ('skl,pdn 14.05.2002 OCC55'; "
               "'skl 29.03.2010 (OCC21623)' LeastEdgeSize-based mode)",
    ),
    Quirk(
        id="missing-seam-on-periodic-faces",
        operation="seam",
        quirk="Imported faces on periodic surfaces frequently LACK the seam "
              "edge entirely, leaving the UV domain open and wire "
              "classification wrong.",
        trigger="IGES/STEP faces on cylinders, cones, spheres, toruses "
                "where the source system does not write seams.",
        workaround="Run a dedicated FixMissingSeam pass that constructs the "
                   "seam edge and re-splits the wire before face validity "
                   "checks.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_Face.cxx (':k7 abv 5.01.99' USA60022.igs ent 243, "
               "FixMissingSeam improved)",
    ),
    Quirk(
        id="composeshell-edge-tol-for-coincidence",
        operation="face-heal",
        quirk="Using VERTEX tolerance for coincidence checks while "
              "assembling wire segments disagrees with the segment-position "
              "check and mishandles overlapping edges.",
        trigger="Recomposing shells/faces from Parasolid-origin data with "
                "overlapping edges.",
        workaround="Use the EDGE tolerance (not vertex tolerance) for "
                   "coincidence during wire-segment assembly so both checks "
                   "agree.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_ComposeShell.cxx ('abv 05 Feb 02' face from "
               "Parasolid; 'abv 21 Mar 00' trj3_s1-md-214.stp #2471 "
               "avoid going back)",
    ),
    Quirk(
        id="intersection-tool-always-modifies",
        operation="wire-heal",
        quirk="The self-intersection fixing tool historically MODIFIED the "
              "shape even when it fixed nothing, so callers could not trust "
              "'unchanged' status.",
        trigger="Running FixSelfIntersectWire and using the returned shape "
                "identity to decide whether anything happened.",
        workaround="Track replacements explicitly (count of replaced "
                   "vertices/edges) and only report DONE when a replacement "
                   "actually occurred.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/ShapeFix/"
               "ShapeFix_IntersectionTool.cxx ('gka 06.09.04 BUG 6555', "
               "nbReplaced accounting)",
    ),
    # ------------------------------------------------------------------ #
    # ShapeAnalysis / ShapeConstruct: projection and closure analysis
    # ------------------------------------------------------------------ #
    Quirk(
        id="rational-bspline-closure-by-sampling",
        operation="surface-query",
        quirk="For rational B-spline surfaces, or when boundary knot "
              "multiplicity != degree+1, pole-based closure detection is "
              "unreliable.",
        trigger="Deciding U/V closure of imported B-spline surfaces (e.g. "
                "a U-closed B-spline whose boundary multiplicities are "
                "nonstandard).",
        workaround="Fall back to SAMPLING points on both boundary isolines "
                   "and comparing distances instead of trusting pole "
                   "coincidence.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeAnalysis/ShapeAnalysis_Surface.cxx ('#6 rln 20/02/98' "
               "ProSTEP ug_exhaust-A.stp #18360)",
    ),
    Quirk(
        id="projection-point-densing-near-end",
        operation="projection",
        quirk="Point-to-curve projection with a large precision snaps "
              "interior points to the curve ENDS, densing projected points "
              "near one end and skewing the pcurve.",
        trigger="Projecting sampled points onto a bounded curve when the "
                "adjust-to-ends precision is the file precision.",
        workaround="Only adjust to curve ends within Precision::Confusion() "
                   "unless end-snapping is explicitly requested "
                   "(AdjustToEnds flag).",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeAnalysis/ShapeAnalysis_Curve.cxx (':j8 abv 10 Dec 98' "
               "tr10_r0501_db.stp #9423, three sites)",
    ),
    Quirk(
        id="adjust-periodic-needs-pconfusion",
        operation="projection",
        quirk="Adjusting a parameter range to a periodic curve using the "
              "3D file precision misplaces the range; period adjustment is "
              "a PARAMETRIC problem.",
        trigger="ElCLib::AdjustPeriodic during edge/pcurve range recovery "
                "on periodic curves.",
        workaround="Use Precision::PConfusion() (parametric confusion), "
                   "never the 3D precision, as the AdjustPeriodic "
                   "tolerance.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeAnalysis/ShapeAnalysis_Curve.cxx and DataExchange/"
               "TKDESTEP/StepToTopoDS/StepToTopoDS_GeometricTool.cxx "
               "(':a7 abv 11 Feb 98', 'preci -> PConfusion()')",
    ),
    Quirk(
        id="projection-ignore-singular-points",
        operation="projection",
        quirk="When classifying whether a projected pcurve lies on a "
              "surface bound, points that fall IN a singularity give "
              "meaningless UV and corrupt the on-bound vote.",
        trigger="Projecting a 3D curve onto a periodic surface whose "
                "samples pass near poles/apexes.",
        workaround="Skip degenerated (singular) sample points entirely when "
                   "deciding bound location for the projected pcurve.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeConstruct/ShapeConstruct_ProjectCurveOnSurface.cxx "
               "('abv 16 Mar 00' trj3_s1-ug.stp #697, U and V branches)",
    ),
    Quirk(
        id="degenerate-projection-minimal-pcurve",
        operation="projection",
        quirk="When too many projected sample points are degenerated, 2D "
              "interpolation of the pcurve is impossible.",
        trigger="Building a pcurve by projection for a curve that runs "
                "along/near a surface singularity.",
        workaround="Degrade gracefully: build a MINIMAL-length pcurve from "
                   "the surviving end points instead of failing the whole "
                   "edge.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKShHealing/"
               "ShapeConstruct/ShapeConstruct_ProjectCurveOnSurface.cxx "
               "('pdn 12.02.99 S4135' minimal-length pcurve branch)",
    ),
    # ------------------------------------------------------------------ #
    # STEP / IGES translators
    # ------------------------------------------------------------------ #
    Quirk(
        id="step-transfer-bind-early-against-cycles",
        operation="step-import",
        quirk="STEP entity graphs can be CYCLIC; recursive transfer without "
              "an early binding loops forever on files with recursive "
              "shape-definition references.",
        trigger="Transferring shape_definition_representation entities that "
                "(indirectly) reference themselves.",
        workaround="Bind a placeholder binder for the entity BEFORE "
                   "recursing so a re-visit finds the binding and stops.",
        source=OCE_REPO + "/src/DataExchange/TKDESTEP/STEPControl/"
               "STEPControl_ActorRead.cxx (':j3 abv 23 Oct 98' rp1sd.stp, "
               "'bind something to protect against loops')",
    ),
    Quirk(
        id="step-shape-aspect-sdr-duplicates",
        operation="step-import",
        quirk="Some systems emit SDRs that only carry SHAPE_ASPECT "
              "validation properties, duplicating real geometry; naive "
              "transfer imports the geometry twice.",
        trigger="AP203/AP214 files with validation-property SDRs whose "
                "representation duplicates another SDR.",
        workaround="Skip SHAPE_ASPECT-only SDRs, but ONLY when their "
                   "representation is duplicated by another SDR (some "
                   "systems use SHAPE_ASPECT for real geometry).",
        source=OCE_REPO + "/src/DataExchange/TKDESTEP/STEPControl/"
               "STEPControl_ActorRead.cxx ('abv 7 Oct 99' TRJ2 comment)",
    ),
    Quirk(
        id="step-edge-explicit-range-after-makeedge",
        operation="step-import",
        quirk="BRepLib_MakeEdge(C,V1,V2,U1,U2) does not always leave the "
              "requested parametric range on the edge for imported curves.",
        trigger="Translating STEP edge_curve entities with explicit "
                "trim parameters.",
        workaround="Explicitly call BRep_Builder::Range(E,U1,U2) on the "
                   "resulting edge after MakeEdge succeeds.",
        source=OCE_REPO + "/src/DataExchange/TKDESTEP/StepToTopoDS/"
               "StepToTopoDS_TranslateEdge.cxx ('abv 14 Mar 00' "
               "trj3_pm1-ug.stp #91739, edge 2)",
    ),
    Quirk(
        id="iges-spline-transform-scope",
        operation="iges-import",
        quirk="Applying the IGES entity transformation matrix at the wrong "
              "stage double-transforms or skips curves; only some entity "
              "kinds still need the explicit transform.",
        trigger="IGES curve transfer with HasTransf() entities (notably "
                "spline curves) after transfer-mode reworks.",
        workaround="Transfer basic curves with mode-transfer OFF and apply "
                   "the location explicitly only for the entity kinds that "
                   "need it (spline curves).",
        source=OCE_REPO + "/src/DataExchange/TKDEIGES/IGESToBRep/"
               "IGESToBRep_TopoCurve.cxx ('14.05.2009 skl for OCC21131'; "
               "'15.03.2011 emv for OCC22294')",
    ),
    Quirk(
        id="iges-offset-surface-bspline-conversion",
        operation="iges-import",
        quirk="IGES offset surfaces do not map to a usable analytic OCCT "
              "surface directly.",
        trigger="Reading IGES type-140 offset surfaces.",
        workaround="Convert the offset surface to a B-spline approximation "
                   "during transfer instead of keeping Geom_OffsetSurface.",
        source=OCE_REPO + "/src/DataExchange/TKDEIGES/IGESToBRep/"
               "IGESToBRep_TopoSurface.cxx ('#12 smh 12.12.99 FRA62468', "
               "conversion to B-Spline for Offset surface)",
    ),
    # ------------------------------------------------------------------ #
    # Modeling algorithms outside healing
    # ------------------------------------------------------------------ #
    Quirk(
        id="surface-walker-local-resolution",
        operation="intersection",
        quirk="The surface-surface intersection marching walker can stall "
              "or step wrongly when using only GLOBAL surface resolution "
              "for its step control.",
        trigger="Marching intersection (IntWalk_PWalking) across surfaces "
                "whose local metric differs strongly from the global one.",
        workaround="Recompute a LOCAL resolution at the current point when "
                   "the step saturates at its initial bound and rescale the "
                   "step from it.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKGeomAlgo/IntWalk/"
               "IntWalk_PWalking.cxx ('for OCC26717', local resolution "
               "block)",
    ),
    Quirk(
        id="loft-conic-sections-param-range",
        operation="loft",
        quirk="Treating loft section curves as 'same conic' while their "
              "parameter RANGES differ produces a wrong ruled/conic "
              "surface.",
        trigger="GeomFill_NSections over circular/conic sections whose "
                "first/last parameters are not identical.",
        workaround="Only take the analytic conic shortcut when first/last "
                   "parameters of all sections agree within PConfusion; "
                   "otherwise use the general B-spline path.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKGeomAlgo/GeomFill/"
               "GeomFill_NSections.cxx ('jgv, 18.02.2009 for OCC20866')",
    ),
    Quirk(
        id="seam-requires-two-pcurves-same-surface",
        operation="seam",
        quirk="BRep_Tool::IsClosed(edge,face) is TRUE both for a real seam "
              "and for an edge shared by two faces built on the SAME "
              "surface; treating the latter as a seam breaks surface "
              "replacement.",
        trigger="Rebuilding shapes (BRepTools_Modifier) where an edge lies "
                "on two distinct faces of one underlying surface.",
        workaround="Only treat an edge as a seam when it genuinely carries "
                   "TWO pcurves on the same face (IsReallyClosed), not "
                   "merely IsClosed.",
        source=OCE_REPO + "/src/ModelingData/TKBRep/BRepTools/"
               "BRepTools_Modifier.cxx ('see OCC21772' two-pcurves check)",
    ),
    Quirk(
        id="fillet-corner-orientation-composition",
        operation="fillet",
        quirk="Corner (three-edge vertex) fillet construction composed edge "
              "orientations from the wrong face when the prolonged arc's "
              "faces coincide, flipping interference orientation.",
        trigger="ChFi3d corner fillets where the prolongation arc's "
                "adjacent faces are the same face.",
        workaround="Recover the arc orientation by exploring the actual "
                   "face's edges instead of reusing the opposite-arc "
                   "orientation.",
        source=OCE_REPO + "/src/ModelingAlgorithms/TKFillet/ChFi3d/"
               "ChFi3d_Builder_C1.cxx ('Modified by skv - Thu Aug 21 ... "
               "OCC20222 Begin/End' blocks)",
    ),
)


# --------------------------------------------------------------------------- #
# lookups
# --------------------------------------------------------------------------- #

def quirks_for_operation(operation: str) -> List[Quirk]:
    """All catalogued quirks for an operation family (e.g. ``"pcurve"``)."""
    op = operation.strip().lower()
    return [q for q in OCE_QUIRKS if q.operation == op]


def quirk_by_id(quirk_id: str) -> Optional[Quirk]:
    for q in OCE_QUIRKS:
        if q.id == quirk_id:
            return q
    return None


def operations() -> List[str]:
    """Sorted unique operation families present in the catalog."""
    return sorted({q.operation for q in OCE_QUIRKS})


# --------------------------------------------------------------------------- #
# selfcheck
# --------------------------------------------------------------------------- #

def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="OCCT kernel-quirk catalog mined from the OCE/OCCT "
                    "sources (reviewer tags + Mantis bug ids); LGPL-2.1 "
                    "with OCCT exception, facts-with-citation only.",
    )
    parser.add_argument("--selfcheck", action="store_true",
                        help="assert catalog integrity (schema completeness, "
                             "unique ids, citations) and exercise lookups.")
    args = parser.parse_args(list(argv) if argv is not None else None)
    if not args.selfcheck:
        parser.print_help()
        return 0

    # 1. Catalog integrity: non-empty, unique ids, every field populated,
    #    every source cites a file inside the mined repo.
    assert len(OCE_QUIRKS) >= 15, len(OCE_QUIRKS)
    ids = [q.id for q in OCE_QUIRKS]
    assert len(ids) == len(set(ids)) == 30, ids
    for q in OCE_QUIRKS:
        for f in (q.id, q.operation, q.quirk, q.trigger, q.workaround,
                  q.source):
            assert f and isinstance(f, str), q.id
        assert OCE_REPO in q.source, q.id       # citation names the repo
        assert "/src/" in q.source, q.id        # ... and a source path
        assert q.id == q.id.lower(), q.id       # kebab-case ids
        d = q.to_dict()
        assert set(d) == {"id", "operation", "quirk", "trigger",
                          "workaround", "source"}, q.id
        # ASCII-only guarantee for every field.
        for v in d.values():
            v.encode("ascii")
    print(f"[selfcheck] catalog: {len(OCE_QUIRKS)} quirks, unique ids, "
          f"all cited into {OCE_REPO}")

    # 2. Every source carries a reviewer tag or Mantis/customer-case marker.
    markers = ("abv", "pdn", "skl", "gka", "rln", "jgv", "smh", "emv",
               "skv", "OCC2", "OCC5", "OCC7", "OCC1", "BUC", "PRO", "TRJ")
    for q in OCE_QUIRKS:
        assert any(m in q.source for m in markers), q.id
    print("[selfcheck] every row carries a reviewer tag or bug/case id")

    # 3. Lookups.
    assert quirk_by_id("pcurve-self-intersection-loops") is not None
    assert quirk_by_id("nope") is None
    assert len(quirks_for_operation("pcurve")) == 3
    assert len(quirks_for_operation("wire-heal")) == 7
    assert len(quirks_for_operation("projection")) == 4
    assert len(quirks_for_operation("step-import")) == 3
    ops = operations()
    assert "seam" in ops and "fillet" in ops and "loft" in ops, ops
    assert sum(len(quirks_for_operation(o)) for o in ops) == len(OCE_QUIRKS)
    print(f"[selfcheck] lookups over {len(ops)} operation families: {ops}")

    # 4. No overlap with the sibling client-side catalog's ids (kept in sync
    #    by convention; ids there are boolean/revolve/loft/face-query themed).
    sibling_ids = {
        "boolean-fuzzy-value", "revolve-zero-degrees",
        "infinite-face-center-sentinel", "saddle-boolean-adjacent-holes",
        "revolve-touching-axis", "loft-invalid-solid",
        "no-occt-booleans-for-metrics", "bbox-near-tangent-refusal",
    }
    assert not sibling_ids.intersection(ids)
    print("[selfcheck] disjoint from occt_quirks.py client-side catalog")
    print("[selfcheck] OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
