"""The driver: a pressure ``results.json`` in, a training corpus out.

No new inference. Every trajectory in the corpus was generated by a real model,
against a real brief, in an experiment that has already been run and published.
The pressure run's 223 attempts were cached for *reproducibility* and reported for
a *headline*, and then discarded. This module keeps them.

What it does per attempt:

1.  Lift the ``(brief, prompt, op_stream, diagnostics, feedback)`` tuple out of
    the results file -- the same tuple the loop's ``on_attempt`` hook would hand
    over live (see :mod:`selftrain.trajectory`).
2.  Re-adjudicate it with :func:`selftrain.ledger.certify` -- the CONJUNCTION of
    the output gate, the envelope grader and the shape metric. The verdicts in
    ``results.json`` are the v1 grader's: envelope-only, no gate, no IoU. They are
    not used.
3.  Find the FIRST DIVERGENCE (:mod:`selftrain.divergence`) and assign the book's
    per-step rewards: +1 to the correct prefix, -1 to the divergent op and to it
    alone, 0 after.
4.  Compute ``tool_reward.aggregate_reward`` -- ``R = alpha*R_ORM +
    beta*mean(R_step) + gamma*R_format`` -- which has existed, complete and
    unit-tested, with a dispatch table and its own test as its only importers.
    This module is its first real caller.

Deterministic. Re-running it on the same results file produces the same corpus,
byte for byte.

    python -m harnesscad.agents.selftrain.corpus \\
        --results assets/pressure/results.json --out assets/selftrain
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, Iterable, List, Optional, Sequence

from harnesscad.agents.agent.tool_reward import aggregate_reward
from harnesscad.agents.agent.tool_schema import InterfaceResult, ToolCall
from harnesscad.agents.agent.tool_trajectory import ToolTrajectory, TrajectoryStep
from harnesscad.agents.selftrain import SCHEMA_VERSION, divergence, ledger
from harnesscad.agents.selftrain import preference as pref_mod
from harnesscad.agents.selftrain import rft as rft_mod
from harnesscad.agents.selftrain.trajectory import (
    AttemptCapture,
    Trajectory,
    capture_from_pressure_record,
    trajectory_id,
    write_jsonl,
)

__all__ = ["build_trajectory", "build_corpus", "main"]

#: ``tool_reward``'s format term measures TOOLCAD's ReAct tag order
#: (<think> -> <tool_call> -> <tool_response>). The pressure prompt asks for a bare
#: JSON array of ops, so ``check_format_order`` is False on every completion in
#: this corpus and ``R_format`` is identically 0. The term is WIRED, not faked: it
#: will start carrying information the moment the loop emits ReAct, and until then
#: the honest value is zero and the report says so.
GAMMA = 1.0
ALPHA = 1.0
BETA = 1.0


def _tool_trajectory(ops: Sequence[dict],
                     report: divergence.DivergenceReport,
                     completed: bool) -> ToolTrajectory:
    """The op stream as a ``ToolTrajectory``, so ``tool_reward`` can score it.

    The step's success label is the KERNEL's -- did this op apply -- which is
    exactly what TOOLCAD's step-wise execution reward is defined to be ("1 only
    when the CAD engine returns 'Success' for the primitive execution").
    """
    traj = ToolTrajectory(completed=completed)
    for k, op in enumerate(ops):
        analysis = next((s for s in report.steps if s.index == k), None)
        ok = bool(analysis.applied) if analysis else False
        detail = (analysis.detail if analysis else "not reached") or (
            "Success" if ok else "fail")
        traj.add(TrajectoryStep(
            think="",
            call=ToolCall(name=str(op.get("op") or "?"),
                          arguments={k2: v for k2, v in op.items() if k2 != "op"}),
            result=InterfaceResult(ok, detail if not ok else "Success"),
        ))
    return traj


def _prompt_for(brief: Any, capture: AttemptCapture,
                previous_feedback: Optional[str]) -> str:
    """The user turn this attempt actually saw.

    Attempt 1 sees the brief. Attempt n>1 sees the brief plus whatever the arm
    handed back after attempt n-1 -- which is the ONE thing the two arms differ in,
    and is therefore the thing a trained model would learn to condition on. It is
    kept verbatim, including the false diagnostics: a corpus that quietly cleaned
    up the feedback would be a corpus that hid the experiment's finding.
    """
    text = getattr(brief, "text", "") or ""
    if capture.attempt <= 1 or not previous_feedback:
        return text
    return "%s\n\n---\n%s" % (text, previous_feedback)


def build_trajectory(brief: Any, capture: AttemptCapture,
                     previous_feedback: Optional[str] = None,
                     *, differential: bool = False) -> Trajectory:
    """One graded trajectory: certify, find the divergence, aggregate the reward."""
    t = Trajectory(
        schema=SCHEMA_VERSION,
        trajectory_id=trajectory_id(capture.model, capture.loop,
                                    capture.brief_id, capture.attempt,
                                    capture.seed),
        brief_id=capture.brief_id,
        brief_text=getattr(brief, "text", ""),
        model=capture.model,
        loop=capture.loop,
        seed=capture.seed,
        attempt=capture.attempt,
        prompt=_prompt_for(brief, capture, previous_feedback),
        raw=capture.raw,
        ops=[dict(o) for o in capture.ops],
        parse_ok=capture.parse_ok,
        parse_error=capture.parse_error,
        diagnostics=[dict(d) for d in capture.diagnostics],
        feedback=capture.feedback,
    )
    if not t.parse_ok or not t.ops:
        t.verdict = ledger.Certificate(
            reasons=["the model's output did not parse into operations"],
            blind_spots=["no geometry was produced; no instrument was consulted"],
        ).to_dict()
        return t

    cert = ledger.certify(brief, t.ops, differential=differential)
    t.verdict = cert.to_dict()
    t.measurements = dict(cert.measurements)

    report = divergence.analyse(brief, t.ops)
    t.first_divergence = report.first_divergence
    t.divergence_detail = report.detail
    t.step_rewards = [s.to_dict()
                      for s in divergence.step_rewards(report, t.ops)]

    tool_traj = _tool_trajectory(t.ops, report, completed=bool(cert.apply_ok))
    reward = aggregate_reward(tool_traj, orm_verdict=cert.accepted,
                              format_text=capture.raw,
                              alpha=ALPHA, beta=BETA, gamma=GAMMA)
    t.reward_outcome = reward.outcome
    t.reward_step_mean = reward.step_mean
    t.reward_format = reward.fmt
    t.reward_total = reward.total
    return t


def build_corpus(results: Dict[str, Any], *,
                 differential: bool = False,
                 progress=None) -> List[Trajectory]:
    """Grade every attempt in a pressure results file."""
    from harnesscad.eval.pressure import briefs as briefs_mod

    out: List[Trajectory] = []
    cells = results.get("results", [])
    for i, cell in enumerate(cells):
        try:
            brief = briefs_mod.brief_by_id(str(cell["brief"]))
        except Exception:                                 # noqa: BLE001
            continue
        previous_feedback: Optional[str] = None
        for record in cell.get("records", []):
            capture = capture_from_pressure_record(cell, record)
            out.append(build_trajectory(brief, capture, previous_feedback,
                                        differential=differential))
            previous_feedback = record.get("feedback")
        if progress is not None:
            progress(i + 1, len(cells))
    return out


# --------------------------------------------------------------------------- #
# manifest
# --------------------------------------------------------------------------- #
def manifest(trajectories: Sequence[Trajectory],
             dpo: Sequence[Any], kto: Sequence[Any],
             rft: Sequence[Any], rationalized: Sequence[Any]) -> Dict[str, Any]:
    parsed = [t for t in trajectories if t.parse_ok and t.ops]
    diverged = [t for t in parsed if t.first_divergence is not None]
    by_op: Dict[str, int] = {}
    for t in diverged:
        k = t.first_divergence
        if k is not None and k < len(t.ops):
            tag = str(t.ops[k].get("op") or "?")
            by_op[tag] = by_op.get(tag, 0) + 1
    return {
        "schema": SCHEMA_VERSION,
        "oracle_ledger": [i.to_dict() for i in ledger.INSTRUMENTS],
        "reference_free_instruments": list(ledger.REFERENCE_FREE),
        "reference_bound_instruments": list(ledger.REFERENCE_BOUND),
        "distribution_warning": rft_mod.DISTRIBUTION_WARNING,
        "counts": {
            "trajectories": len(trajectories),
            "parsed": len(parsed),
            "unparseable": len(trajectories) - len(parsed),
            "rft_records": len(rft),
            "rationalized_records": len(rationalized),
            "dpo_pairs": len(dpo),
            "kto_records": len(kto),
        },
        "acceptance": rft_mod.acceptance_stats(trajectories),
        "preference": pref_mod.preference_stats(dpo, kto),
        "divergence": {
            "streams_with_a_divergence": len(diverged),
            "streams_clean": len(parsed) - len(diverged),
            "first_divergence_by_op": dict(sorted(by_op.items())),
            "mean_first_divergence_index": (
                sum(t.first_divergence or 0 for t in diverged) / len(diverged)
                if diverged else None),
        },
        "reward": {
            "note": (
                "tool_reward.aggregate_reward is R = alpha*R_ORM + "
                "beta*mean(R_step) + gamma*R_format. R_format is identically 0 "
                "across this corpus: it measures TOOLCAD's ReAct tag order and "
                "the pressure prompt asks for a bare JSON array. The term is "
                "wired, not faked."),
            "alpha": ALPHA, "beta": BETA, "gamma": GAMMA,
            "mean_total": (sum(t.reward_total for t in parsed) / len(parsed)
                           if parsed else 0.0),
            "mean_outcome": (sum(t.reward_outcome for t in parsed) / len(parsed)
                             if parsed else 0.0),
            "mean_step": (sum(t.reward_step_mean for t in parsed) / len(parsed)
                          if parsed else 0.0),
            "mean_format": (sum(t.reward_format for t in parsed) / len(parsed)
                            if parsed else 0.0),
        },
    }


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main(argv: Optional[Sequence[str]] = None) -> int:
    from harnesscad.eval.pressure import briefs as briefs_mod

    ap = argparse.ArgumentParser(
        prog="harnesscad-selftrain",
        description="Build the self-training corpus from a pressure results.json.")
    ap.add_argument("--results", default="assets/pressure/results.json")
    ap.add_argument("--out", default="assets/selftrain")
    ap.add_argument("--differential", action="store_true",
                    help="also consult the six-engine differential oracle (slow)")
    ap.add_argument("--limit", type=int, default=0,
                    help="grade only the first N cells (for a smoke run)")
    args = ap.parse_args(list(argv) if argv is not None else None)

    with open(args.results, "r", encoding="utf-8") as fh:
        results = json.load(fh)
    if args.limit:
        results = dict(results, results=results["results"][:args.limit])

    def progress(done: int, total: int) -> None:
        sys.stderr.write("\rgrading cell %d/%d" % (done, total))
        sys.stderr.flush()

    trajectories = build_corpus(results, differential=args.differential,
                                progress=progress)
    sys.stderr.write("\n")

    rft = rft_mod.build(trajectories, policy="full")
    solved_briefs = {t.brief_id for t in trajectories if t.accepted}
    all_briefs = {t.brief_id for t in trajectories}
    unsolved = [briefs_mod.brief_by_id(b)
                for b in sorted(all_briefs - solved_briefs)]
    rationalized = rft_mod.rationalized_records(unsolved)
    dpo = pref_mod.build_dpo(trajectories, strict=True)
    kto = pref_mod.build_kto(trajectories)

    os.makedirs(args.out, exist_ok=True)
    write_jsonl(os.path.join(args.out, "trajectories.jsonl"), trajectories)
    _write_rows(os.path.join(args.out, "rft.jsonl"), rft)
    _write_rows(os.path.join(args.out, "rft_rationalized.jsonl"), rationalized)
    _write_rows(os.path.join(args.out, "dpo.jsonl"), dpo)
    _write_rows(os.path.join(args.out, "kto.jsonl"), kto)

    man = manifest(trajectories, dpo, kto, rft, rationalized)
    with open(os.path.join(args.out, "manifest.json"), "w",
              encoding="utf-8", newline="\n") as fh:
        json.dump(man, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(json.dumps(man["counts"], indent=2, sort_keys=True))
    print(json.dumps(man["acceptance"], indent=2, sort_keys=True))
    print(json.dumps(man["divergence"], indent=2, sort_keys=True))
    return 0


def _write_rows(path: str, rows: Iterable[Any]) -> int:
    n = 0
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        for r in rows:
            fh.write(json.dumps(r.to_dict(), sort_keys=True))
            fh.write("\n")
            n += 1
    return n


if __name__ == "__main__":                                # pragma: no cover
    raise SystemExit(main())
