"""Bevel-gear cone geometry and the spherical involute (deterministic).

Source rule: the ``gear_generator`` plugin of the CadQuery community plugin
collection.  Its ``Gear`` class is an ordinary planar involute spur/helical
gear (already covered by ``geometry/cadgpt_involute_gear.py``), but its
``BevelGear`` and ``BevelGearSystem`` classes carry geometry the harness does
not have: a *bevel* gear whose teeth lie on a cone, generated by the
**spherical involute** rather than the planar one, and the pairing math that
places two bevel gears so their axes meet and their teeth mesh.

The harness already has a *taper-scale* approximation of a bevel gear
(``geometry/cadgpt_gear_train.py::bevel_scale``, a linear-extrude cone shrink)
and the planar spur geometry; neither computes true bevel cone angles or the
spherical involute.  This module supplies that missing, fully deterministic
layer.  Angles are in DEGREES on the public surface (converted internally).

Cone-angle relations (module ``m``, teeth ``z``, pressure angle ``alpha``,
pitch cone angle ``delta_p``, back-cone / mounting sphere radius ``R``):

    base cone angle   delta_b = asin(sin(delta_p) * cos(alpha))
    addendum angle    theta_a = atan2(m,        R)
    dedendum angle    theta_f = atan2(1.25 * m, R)
    face  cone angle  delta_a = delta_p + theta_a
    root  cone angle  delta_f = delta_p - theta_f
    tip   circle r    r_a = R * sin(delta_a)
    root  circle r    r_f = R * sin(delta_f)
    pitch circle r    r_p = R * sin(delta_p)   (== m*z/2)
    tooth half-thick  theta_p = pi*m / (R*sin(delta_p)) / 4   (rotation, rad)

Meshing pair on a shaft angle ``Sigma`` (default 90 degrees), pinion ``z1``
and wheel ``z2`` (``z1 <= z2``):

    delta_p1 = atan2(sin Sigma, z2/z1 + cos Sigma)     (pinion pitch cone)
    delta_p2 = Sigma - delta_p1                         (wheel  pitch cone)
    R        = (m * z2 / 2) / sin(delta_p2)             (common cone distance)

For ``Sigma = 90`` this reduces to ``delta_p1 = atan2(z1, z2)`` exactly as the
plugin computes it.  Stdlib-only, deterministic.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Tuple

Point3 = Tuple[float, float, float]

__all__ = [
    "BevelGearError",
    "base_cone_angle",
    "addendum_angle",
    "dedendum_angle",
    "spherical_involute",
    "pitch_cone_angles",
    "cone_distance",
    "BevelGear",
    "BevelGearPair",
]


class BevelGearError(ValueError):
    """Raised for bevel-gear parameters that cannot form a valid gear."""


def base_cone_angle(delta_p_deg: float, alpha_deg: float = 20.0) -> float:
    """Base cone angle ``delta_b = asin(sin(delta_p) * cos(alpha))`` (degrees)."""
    dp = math.radians(delta_p_deg)
    a = math.radians(alpha_deg)
    s = math.sin(dp) * math.cos(a)
    if not -1.0 <= s <= 1.0:
        raise BevelGearError("degenerate base cone angle")
    return math.degrees(math.asin(s))


def addendum_angle(module: float, cone_distance: float) -> float:
    """Addendum angle ``theta_a = atan2(m, R)`` (degrees)."""
    if module <= 0.0 or cone_distance <= 0.0:
        raise BevelGearError("module and cone distance must be positive")
    return math.degrees(math.atan2(module, cone_distance))


def dedendum_angle(module: float, cone_distance: float) -> float:
    """Dedendum angle ``theta_f = atan2(1.25*m, R)`` (degrees)."""
    if module <= 0.0 or cone_distance <= 0.0:
        raise BevelGearError("module and cone distance must be positive")
    return math.degrees(math.atan2(1.25 * module, cone_distance))


def spherical_involute(delta_deg: float, delta_b_deg: float,
                       radius: float) -> Point3:
    """A point on the spherical involute lying on a sphere of ``radius``.

    Faithful port of the plugin's ``spherical_involute`` helper.  ``delta``
    sweeps from the base cone angle up to the face cone angle; ``delta_b`` is
    the base cone angle.  Both are in degrees.
    """
    delta = math.radians(delta_deg)
    delta_b = math.radians(delta_b_deg)
    if radius <= 0.0:
        raise BevelGearError("radius must be positive")
    sdb = math.sin(delta_b)
    if abs(sdb) < 1e-12:
        raise BevelGearError("base cone angle too small for spherical involute")
    ratio = math.cos(delta) / math.cos(delta_b)
    if not -1.0 <= ratio <= 1.0:
        raise BevelGearError("delta below the base cone angle")
    theta = math.acos(ratio) / sdb
    ct, st = math.cos(theta), math.sin(theta)
    x = (radius * math.cos(theta * sdb) * sdb * ct
         - radius * math.sin(theta * sdb) * (-st))
    y = (radius * math.cos(theta * sdb) * sdb * st
         - radius * math.sin(theta * sdb) * ct)
    z = radius * math.cos(theta * sdb) * math.cos(delta_b)
    return (x, y, z)


def pitch_cone_angles(z1: int, z2: int,
                      shaft_angle_deg: float = 90.0) -> Tuple[float, float]:
    """Pitch cone angles ``(delta_p1, delta_p2)`` in degrees for a meshing pair.

    ``z1`` is the pinion (fewer teeth) and ``z2`` the wheel; if given the other
    way round they are swapped, matching the plugin.  For a right-angle drive
    (``shaft_angle_deg == 90``) this is ``atan2(z1, z2)`` and its complement.
    """
    if z1 < 1 or z2 < 1:
        raise BevelGearError("teeth counts must be positive")
    if z1 > z2:
        z1, z2 = z2, z1
    sigma = math.radians(shaft_angle_deg)
    dp1 = math.atan2(math.sin(sigma), (z2 / z1) + math.cos(sigma))
    dp2 = sigma - dp1
    return (math.degrees(dp1), math.degrees(dp2))


def cone_distance(module: float, teeth: int, delta_p_deg: float) -> float:
    """Common cone distance ``R = (m*z/2) / sin(delta_p)``."""
    if module <= 0.0 or teeth < 1:
        raise BevelGearError("module and teeth must be positive")
    s = math.sin(math.radians(delta_p_deg))
    if abs(s) < 1e-12:
        raise BevelGearError("pitch cone angle too small")
    return (module * teeth / 2.0) / s


@dataclass(frozen=True)
class BevelGear:
    """Derived cone geometry for a single bevel gear.

    ``module`` ``m``, ``teeth`` ``z``, ``face_width`` ``b`` (measured inward
    along the cone), ``pitch_cone_angle`` ``delta_p`` (degrees),
    ``cone_distance`` ``R`` (mounting sphere radius at the pitch circle) and
    ``pressure_angle`` ``alpha`` (degrees).
    """

    module: float
    teeth: int
    face_width: float
    pitch_cone_angle: float
    cone_distance: float
    pressure_angle: float = 20.0

    def __post_init__(self) -> None:
        if self.module <= 0.0:
            raise BevelGearError("module must be positive")
        if self.teeth < 1:
            raise BevelGearError("teeth must be >= 1")
        if self.face_width <= 0.0 or self.face_width >= self.cone_distance:
            raise BevelGearError("face_width must be in (0, cone_distance)")
        if not 0.0 < self.pitch_cone_angle < 90.0:
            raise BevelGearError("pitch_cone_angle must be in (0, 90) degrees")

    @property
    def pitch_radius(self) -> float:
        """Pitch circle radius ``m*z/2`` (== R*sin(delta_p))."""
        return self.module * self.teeth / 2.0

    @property
    def inner_cone_distance(self) -> float:
        """Cone distance at the small (inner) end: ``R - b``."""
        return self.cone_distance - self.face_width

    @property
    def base_cone_angle(self) -> float:
        return base_cone_angle(self.pitch_cone_angle, self.pressure_angle)

    @property
    def addendum_angle(self) -> float:
        return addendum_angle(self.module, self.cone_distance)

    @property
    def dedendum_angle(self) -> float:
        return dedendum_angle(self.module, self.cone_distance)

    @property
    def face_cone_angle(self) -> float:
        """Tip (face) cone angle ``delta_a = delta_p + theta_a`` (degrees)."""
        return self.pitch_cone_angle + self.addendum_angle

    @property
    def root_cone_angle(self) -> float:
        """Root cone angle ``delta_f = delta_p - theta_f`` (degrees)."""
        return self.pitch_cone_angle - self.dedendum_angle

    @property
    def tip_radius(self) -> float:
        """Tip circle radius ``R * sin(delta_a)``."""
        return self.cone_distance * math.sin(math.radians(self.face_cone_angle))

    @property
    def root_radius(self) -> float:
        """Root circle radius ``R * sin(delta_f)``."""
        return self.cone_distance * math.sin(math.radians(self.root_cone_angle))

    @property
    def tooth_thickness_angle(self) -> float:
        """Rotation ``theta_p`` (radians) giving pitch tooth thickness ``p/2``.

        ``theta_p = pi*m / (R*sin(delta_p)) / 4`` -- the plugin's ``theta_p``.
        """
        rp = self.cone_distance * math.sin(math.radians(self.pitch_cone_angle))
        return (math.pi * self.module) / rp / 4.0

    def default_clearance(self) -> float:
        """Plugin default backing clearance ``m*z/10``."""
        return self.module * self.teeth / 10.0

    def tooth_profile_point(self, delta_deg: float, radius: float = None) -> Point3:
        """Point on this gear's tooth flank (spherical involute) at ``delta``."""
        r = self.cone_distance if radius is None else radius
        return spherical_involute(delta_deg, self.base_cone_angle, r)


@dataclass(frozen=True)
class BevelGearPair:
    """A meshing bevel pinion + wheel sharing a common cone distance.

    Mirrors the plugin's ``BevelGearSystem``: the two gears have the same
    ``module``, their pitch cones sum to the shaft angle, and both sit on the
    same cone distance ``R`` so the teeth meet.
    """

    module: float
    pinion_teeth: int
    wheel_teeth: int
    face_width: float
    shaft_angle: float = 90.0
    pressure_angle: float = 20.0

    def __post_init__(self) -> None:
        if self.module <= 0.0:
            raise BevelGearError("module must be positive")
        if self.pinion_teeth < 1 or self.wheel_teeth < 1:
            raise BevelGearError("teeth counts must be positive")
        z1, z2 = self.pinion_teeth, self.wheel_teeth
        if z1 > z2:
            object.__setattr__(self, "pinion_teeth", z2)
            object.__setattr__(self, "wheel_teeth", z1)

    @property
    def gear_ratio(self) -> float:
        """Speed-reduction ratio ``z2 / z1`` (>= 1)."""
        return self.wheel_teeth / self.pinion_teeth

    @property
    def pitch_cone_angles(self) -> Tuple[float, float]:
        return pitch_cone_angles(self.pinion_teeth, self.wheel_teeth,
                                 self.shaft_angle)

    @property
    def cone_distance(self) -> float:
        _dp1, dp2 = self.pitch_cone_angles
        return cone_distance(self.module, self.wheel_teeth, dp2)

    def pinion(self) -> BevelGear:
        dp1, _dp2 = self.pitch_cone_angles
        return BevelGear(self.module, self.pinion_teeth, self.face_width,
                         dp1, self.cone_distance, self.pressure_angle)

    def wheel(self) -> BevelGear:
        _dp1, dp2 = self.pitch_cone_angles
        return BevelGear(self.module, self.wheel_teeth, self.face_width,
                         dp2, self.cone_distance, self.pressure_angle)
